"""fix

Revision ID: cc66d0959893
Revises: 
Create Date: 2020-05-30 03:49:36.226296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc66d0959893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_restoran', sa.Column('restoran_pilihan', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_restoran', 'restoran_pilihan')
    # ### end Alembic commands ###
